apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kms
  name: backend-deployment-test
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mstar228/backend:latest
          ports:
            - containerPort: 8080